### ISSUE TITLE
Subject Alt Name missing in sample server certificates

### ISSUE THREAD

**Issue by ghost** [davechri/middleman-proxy#97]
Great work!

It would be nice to be able to start testing the tool using your provided certs without browser errors on **https** interception requests :)

Currently due to a lack of a subject alt name, the browser won't really acknowledge server.crt as secure, and won't allow tls interception.

Please refer to [stackoverflow-43665243](https://stackoverflow.com/questions/43665243/invalid-self-signed-ssl-cert-subject-alternative-name-missing)

**Comment by davechri** [comment]
All certificates are now generated by the https://github.com/joeferner/node-http-mitm-proxy package.  You can import the middleman-proxy/.http-mitm-proxy/certs/ca.pem to your browser, so that the generated certificates are trusted by your browser.
