### ISSUE TITLE
General TCP+TLS Documentation?

### ISSUE THREAD

**Issue by ghost** [davechri/middleman-proxy#98]
Can this library support TCP + TLS communications? is it under "other"?

Would be nice to see some clarification in this! thanks!

**Comment by davechri** [comment]
Sorry to take so long to respond.   I recently started using the https://github.com/joeferner/node-http-mitm-proxy package to support https, and manage the certificates.  The Middleman proxy listens on port 9999 (default) for incoming HTTP Connect requests (https tunnel), and https requests.  Your browser proxy can be configured to proxy https to localhost:9999.  Backend microservices can also be configured to send https messages to localhost:9999.

The https: tab configures URL paths to route https messages received from a microservice to the origin server.  The proxy: tab by default captures all https traffic from the browser.   

I hope that helps.
